### ISSUE TITLE
Ruby 2.4 breaks creation of invoices without shipping and tax rate

### ISSUE THREAD

**Issue by dpoetzsch** [commondream/payday#53]
The following won't work in ruby 2.4:

```ruby
pdf_invoice = Payday::Invoice.new(invoice_number: '1234')
```

The error is:

```
     ArgumentError:
       invalid value for BigDecimal(): ""
     # /home/dph/.gem/ruby/2.4.0/gems/payday-1.1.5/lib/payday/invoice.rb:34:in `initialize'
     # /home/dph/.gem/ruby/2.4.0/gems/payday-1.1.5/lib/payday/invoice.rb:34:in `new'
     # /home/dph/.gem/ruby/2.4.0/gems/payday-1.1.5/lib/payday/invoice.rb:34:in `shipping_rate='
     # /home/dph/.gem/ruby/2.4.0/gems/payday-1.1.5/lib/payday/invoice.rb:15:in `initialize'
     # ./app/lib/pdf_invoice.rb:11:in `new'
```

The reason is the following:

This used to work in ruby 2.3:
```
irb(main):003:0> BigDecimal.new ''
=> #<BigDecimal:5627144d57b0,'0.0',9(9)>
```

It no longer does in ruby 2.4:
```
irb(main):002:0>  BigDecimal.new ''
ArgumentError: invalid value for BigDecimal(): ""
	from (irb):2:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
```

I can create a pull request to fix this issue

**Comment by nguyenchiencong** [comment]
Shouldn't this be merged?
